Allow null value in config map
Ignore the null variable when calculating hash to work around error:
Error: Invalid template interpolation value
│
│   on vendor/modules/aks/aks/application_configuration/resources.tf line 13, in locals:
│   13:   config_map_hash = sha1(join("-", [for k, v in local.config_map_data : "$***k***:$***v***"]))
│
│ The expression result is null. Cannot include a null value in a string
│ template.

We use the same behaviour for secrets