Specify StatusCake provider
We need to specify the provider explicitly as Terraform can't guess the
name as it's not in the `hashicorp` group. This should fix the following
error:

```
Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/statuscake: provider registry registry.terraform.io does not
│ have a provider named registry.terraform.io/hashicorp/statuscake
│
│ Did you intend to use statuscakedev/statuscake? If so, you must specify that source address in each module which requires that provider.
│ To see which modules are currently depending on hashicorp/statuscake, run the following command:
│     terraform providers
╵
```